# Generated by Django 4.0.2 on 2022-02-05 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('compensation', models.FloatField()),
                ('duties', models.CharField(max_length=200)),
                ('requirements', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('person_id', models.CharField(max_length=20)),
                ('position_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advagency.position')),
            ],
        ),
    ]
